config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  get 'management/index'
  get 'management/chat'
  scope '/management' do
    resources :users
    resources :courses do 
      resources :lessons
    end
  end

  resources :courses

  get 'users/my_account'
  get 'users/edit'
  get 'users/edit_password'

  resources :privacy_policies do
    collection do
      get 'last'
    end
  end
  resources :blog_articles
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', confirmations: 'confirmations' } do
      delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resource :user, only: [:edit_password, :edit] do
    collection do
      patch 'update_password'
      patch 'update'
    end
  end

  resources :application_settings
  resources :alerts
  resources :abouts
  resources :assistances
  resources :articles
  resources :rooms

  get 'home/index', to: 'home#index'
  get 'home/my_home', to: 'home#my_home'
  get 'home/dashboard', to: 'home#dashboard'
  
  get 'rooms/show', to: 'rooms#show'

  root 'home#index'
  
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities


    if user.present?
        can [:my_account, 
            :edit, 
            :update, 
            :edit_password, 
            :update_password], 
            User 
        if user.admin?
            can :manage, :all
        end
    else
        # Usuarios no registrados (visitas)
        can :read, BlogArticle
    end

  end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/alert.rb
class Alert < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/assistance.rb
class Assistance < ApplicationRecord
end

app/models/blog_article.rb
class BlogArticle < ApplicationRecord
  validates :title, :url, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  after_create_commit { BroadcastNoteJob.perform_later self}

end

app/models/privacy_policy.rb
class PrivacyPolicy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end

  #Esto es de el chat
    has_many :messages
    has_many :conversations, foreign_key: :sender_id

end

app/controllers/assistances_controller.rb
class AssistancesController < ApplicationController
  before_action :set_assistance, only: [:show, :edit, :update, :destroy]

  # GET /assistances
  # GET /assistances.json
  def index
    @assistances = Assistance.all
  end

  # GET /assistances/1
  # GET /assistances/1.json
  def show
  end

  # GET /assistances/new
  def new
    @assistance = Assistance.new
  end

  # GET /assistances/1/edit
  def edit
  end

  # POST /assistances
  # POST /assistances.json
  def create
    @assistance = Assistance.new(assistance_params)

    respond_to do |format|
      if @assistance.save
        format.html { redirect_to @assistance, notice: 'Assistance was successfully created.' }
        format.json { render :show, status: :created, location: @assistance }
      else
        format.html { render :new }
        format.json { render json: @assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assistances/1
  # PATCH/PUT /assistances/1.json
  def update
    respond_to do |format|
      if @assistance.update(assistance_params)
        format.html { redirect_to @assistance, notice: 'Assistance was successfully updated.' }
        format.json { render :show, status: :ok, location: @assistance }
      else
        format.html { render :edit }
        format.json { render json: @assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistances/1
  # DELETE /assistances/1.json
  def destroy
    @assistance.destroy
    respond_to do |format|
      format.html { redirect_to assistances_url, notice: 'Assistance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assistance
      @assistance = Assistance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assistance_params
      params.fetch(:assistance, {})
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/assistances_helper.rb
module AssistancesHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assistances/_form.html.erb
<%= form_with(model: assistance, local: true) do |form| %>
  <% if assistance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assistance.errors.count, "error") %> prohibited this assistance from being saved:</h2>

      <ul>
      <% assistance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assistances/edit.html.erb
<h1>Editing Assistance</h1>

<%= render 'form', assistance: @assistance %>

<%= link_to 'Show', @assistance %> |
<%= link_to 'Back', assistances_path %>

app/views/assistances/index.html.erb
<!--<p id="notice"><%= notice %></p>

<h1>Assistances</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistances.each do |assistance| %>
      <tr>
        <td><%= link_to 'Show', assistance %></td>
        <td><%= link_to 'Edit', edit_assistance_path(assistance) %></td>
        <td><%= link_to 'Destroy', assistance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assistance', new_assistance_path %>-->
<%= render 'partials/header' %>

<div class="container">
  <h1 class="gold-title"> ASISTENCIA </h1>

  <div class="acordeon">
    <div class="acordeon__item">
      <input type="checkbox" name="acordeon" id="item1">
      <label for="item1" class="acordeon__titulo">Pregunta 1</label>
      <p class="acordeon__contenido">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic tenetur ratione voluptatibus, aliquam ipsa eligendi nisi culpa quisquam, in quis nostrum quaerat. Iusto placeat, maxime similique voluptatum ullam at pariatur.</p>
    </div>
    <div class="acordeon__item">
      <input type="checkbox" name="acordeon" id="item2">
      <label for="item2" class="acordeon__titulo">Pregunta 2</label>
      <p class="acordeon__contenido">Est culpa ab ut voluptatem deserunt consequuntur eius, rem nesciunt dolorem possimus soluta, sequi, alias, harum. Voluptatem molestias, illo nam aperiam non consequatur, suscipit ab nesciunt ipsa sed consectetur! Maxime!</p>
    </div>
    <div class="acordeon__item">
      <input type="checkbox" name="acordeon" id="item3">
      <label for="item3" class="acordeon__titulo">Pregunta 3</label>
      <p class="acordeon__contenido">Eaque incidunt sed laborum ex quibusdam, impedit labore reprehenderit beatae quidem eum officia. Vero officia dolore nesciunt error, reprehenderit maiores facilis id accusamus quidem alias harum cumque atque, ratione rem?</p>
    </div>
    <div class="acordeon__item">
      <input type="checkbox" name="acordeon" id="item4">
      <label for="item4" class="acordeon__titulo">Pregunta 4</label>
      <p class="acordeon__contenido">Excepturi repudiandae molestiae rem fugit temporibus harum voluptas similique inventore facilis libero voluptatem praesentium quaerat, sunt labore accusamus, illum odio illo eius! Nesciunt hic architecto facere, eaque expedita deserunt consectetur.</p>
    </div>
    <div class="acordeon__item">
      <input type="checkbox" name="acordeon" id="item5">
      <label for="item5" class="acordeon__titulo">Pregunta 5</label>
      <p class="acordeon__contenido">Ullam ea sit tenetur repellendus nesciunt nemo mollitia, fugit consequuntur minima soluta neque quod commodi, cum qui, porro maiores rem tempora omnis aliquid labore itaque? Autem ipsa error quo doloremque.</p>
    </div>
    <div class="acordeon__item">
      <input type="checkbox" name="acordeon" id="item6">
      <label for="item6" class="acordeon__titulo">Pregunta 6</label>
      <p class="acordeon__contenido">Nostrum quae quis eligendi deleniti odio in adipisci placeat voluptas laborum consectetur illo, tempore vitae perferendis, quo voluptatibus blanditiis porro! Animi eveniet pariatur iste esse nobis optio maxime fugiat eum.</p>
    </div>
  </div>



</div>

app/views/assistances/new.html.erb
<h1>New Assistance</h1>

<%= render 'form', assistance: @assistance %>

<%= link_to 'Back', assistances_path %>

app/views/assistances/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_assistance_path(@assistance) %> |
<%= link_to 'Back', assistances_path %>